core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.register, name='register'),
    path("register_dynamic/", views.dynamic_register, name='register_dynamic'),
]

modelchoicedemo/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('core.urls')),
)

core/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django_countries.fields import CountryField


class Car(models.Model):
    manufacturer = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return self.manufacturer

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self._create_user(email, password, **extra_fields)

# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=True, blank=True)
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, null=True)
    car_boolean = models.BooleanField(default=False)

    USERNAME_FIELD ="email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return str(self.email)

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from dynamic_forms import DynamicField, DynamicFormMixin

from core.models import Car, User


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2", "car_boolean", "car")
        widgets = {"home_country": CountrySelectWidget()}


class DynamicUserCreateForm(DynamicFormMixin, forms.Form):
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    car_boolean = forms.BooleanField()
    car = DynamicField(
        forms.ModelChoiceField,
        queryset=Car.objects.all(),
        initial=None
    )
    home_country = CountryField().formfield()
    

core/views.py
from django.shortcuts import redirect, render

from core.forms import DynamicUserCreateForm, UserCreateForm


# Create your views here.
def register(request):
    if request.method == "POST":
        form = UserCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("register")

    context = {"form": UserCreateForm}
    return render(request, 'core/register.html', context)


def dynamic_register(request):
    if request.method == "POST":
        form = DynamicUserCreateForm(request.POST)
        return redirect("register")
    
    context = {"form": DynamicUserCreateForm}
    return render(request, "core/register.html", context)

core/templates/core/base.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script
        src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
        crossorigin="anonymous">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body>
    <div class="container mt-2">
        {% block content %}

        {% endblock %}
    </div>

    {% block scripts %}
    {% endblock %}
</body>
</html>

core/templates/core/register.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Register and Select Cars!</h1>
    <form method="POST">
        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary mt-4">Submit</button>

        {% block scripts %}
        <script>
            $("#id_car").select2()
            $("#id_home_country").select2()
        </script>
        {% endblock %}

    </form>
{% endblock %}

core/templates/core/register_htmx.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h1>Register and Select Cars!</h1>
    <form method="POST">
        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary mt-4">Submit</button>

        {% block scripts %}
        <script>
            $("#id_car").select2()
            $("#id_home_country").select2()
        </script>
        {% endblock %}

    </form>
{% endblock %}